[package]
name = "docknix"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.53"
dkregistry = "0.5.0"
regex = "1.5.5"
rnix = "0.10.1"
serde_json = "1.0.80"
tokio = { version = "0.2", features = ["full"] }
walkdir = "2.3.2"
